"""
Tests for MaunPrekshak Core v0.14.0 — Multi-Ecosystem SCA (.NET NuGet & Dart/Flutter Pub).
"""
import os
import tempfile
import pytest
from unittest.mock import patch, AsyncMock

from maunprekshak.scanner.deps import (
    parse_csproj,
    parse_packages_config,
    parse_packages_lock_json,
    parse_pubspec_yaml,
    parse_pubspec_lock,
    scan_dependencies,
)
from maunprekshak.scanner.report import DepVulnerability, Severity


def test_parse_csproj():
    csproj_content = """<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging">
      <Version>6.0.0</Version>
    </PackageReference>
  </ItemGroup>
</Project>
"""
    with tempfile.NamedTemporaryFile("w", suffix=".csproj", delete=False) as f:
        f.write(csproj_content)
        fname = f.name
    try:
        pkgs = dict(parse_csproj(fname))
        assert pkgs.get("Newtonsoft.Json") == "13.0.1"
        assert pkgs.get("Microsoft.Extensions.Logging") == "6.0.0"
    finally:
        os.unlink(fname)


def test_parse_packages_config():
    config_content = """<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net472" />
  <package id="EntityFramework" version="6.4.4" targetFramework="net472" />
</packages>
"""
    with tempfile.NamedTemporaryFile("w", suffix=".config", delete=False) as f:
        f.write(config_content)
        fname = f.name
    try:
        pkgs = dict(parse_packages_config(fname))
        assert pkgs.get("Newtonsoft.Json") == "12.0.2"
        assert pkgs.get("EntityFramework") == "6.4.4"
    finally:
        os.unlink(fname)


def test_parse_packages_lock_json():
    lock_content = """{
  "version": 1,
  "dependencies": {
    "net6.0": {
      "Newtonsoft.Json": {
        "type": "Direct",
        "resolved": "13.0.1",
        "contentHash": "abc"
      },
      "Serilog": {
        "type": "Direct",
        "resolved": "2.10.0",
        "contentHash": "def"
      }
    }
  }
}
"""
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        f.write(lock_content)
        fname = f.name
    try:
        pkgs = dict(parse_packages_lock_json(fname))
        assert pkgs.get("Newtonsoft.Json") == "13.0.1"
        assert pkgs.get("Serilog") == "2.10.0"
    finally:
        os.unlink(fname)


def test_parse_pubspec_yaml():
    pubspec_content = """name: my_flutter_app
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  path: 1.8.0
  shared_preferences:
    version: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
"""
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
        f.write(pubspec_content)
        fname = f.name
    try:
        pkgs = dict(parse_pubspec_yaml(fname))
        assert "flutter" not in pkgs
        assert "flutter_test" not in pkgs
        assert pkgs.get("http") == "0.13.3"
        assert pkgs.get("path") == "1.8.0"
        assert pkgs.get("shared_preferences") == "2.0.6"
        assert pkgs.get("pedantic") == "1.10.0"
    finally:
        os.unlink(fname)


def test_parse_pubspec_lock():
    lock_content = """# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3"
  meta:
    dependency: "transitive"
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
"""
    with tempfile.NamedTemporaryFile("w", suffix=".lock", delete=False) as f:
        f.write(lock_content)
        fname = f.name
    try:
        pkgs = dict(parse_pubspec_lock(fname))
        assert pkgs.get("http") == "0.13.3"
        assert pkgs.get("meta") == "1.7.0"
    finally:
        os.unlink(fname)


@pytest.mark.asyncio
async def test_scan_dependencies_nuget_and_pub():
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create a csproj file
        csproj_path = os.path.join(tmpdir, "App.csproj")
        with open(csproj_path, "w") as f:
            f.write("""<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
</Project>
""")
        # Create a pubspec.lock file
        pubspec_path = os.path.join(tmpdir, "pubspec.lock")
        with open(pubspec_path, "w") as f:
            f.write("""packages:
  http:
    dependency: "direct main"
    source: hosted
    version: "0.13.0"
""")

        mock_nuget_vuln = DepVulnerability(
            package="Newtonsoft.Json",
            version="12.0.2",
            cve_id="GHSA-5crp-9r3c-p9vr",
            severity=Severity.HIGH.value,
            cvss_score=7.5,
            description="Improper Handling of Exceptional Conditions in Newtonsoft.Json",
            fix_version="13.0.1",
        )
        mock_pub_vuln = DepVulnerability(
            package="http",
            version="0.13.0",
            cve_id="GHSA-pub-1234",
            severity=Severity.MEDIUM.value,
            cvss_score=5.0,
            description="Vulnerability in http package",
            fix_version="0.13.3",
        )

        async def fake_query_osv(package, version, ecosystem):
            if ecosystem == "NuGet" and package == "Newtonsoft.Json":
                return [mock_nuget_vuln]
            elif ecosystem == "Pub" and package == "http":
                return [mock_pub_vuln]
            return []

        with patch("maunprekshak.scanner.deps._query_osv", side_effect=fake_query_osv):
            findings = await scan_dependencies(tmpdir)

        cve_ids = [f.cve_id for f in findings]
        assert "GHSA-5crp-9r3c-p9vr" in cve_ids
        assert "GHSA-pub-1234" in cve_ids
